const fs=require("fs");
const path=require("path");
const root=__dirname;
const base="https://girostobd.github.io";
const urls=["/","/shop/","/about-us","/contact-us","/delivery-policy","/privacy-policy","/refund-and-replacement-policy-girosto","/blog/HealthyLivingBlogGirosto"];
const clean=file=>file.replace(/\.html$/,"");
for(const file of fs.readdirSync(path.join(root,"shop","category")).filter(file=>file.endsWith(".html")).sort())urls.push(`/shop/category/${clean(file)}`);
for(const file of fs.readdirSync(path.join(root,"shop","product")).filter(file=>file.endsWith(".html")).sort())urls.push(`/shop/product/${clean(file)}`);
const xml=['<?xml version="1.0" encoding="UTF-8"?>','<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',...urls.map(url=>`  <url><loc>${base}${url}</loc><changefreq>${url.startsWith("/shop/product/")?"monthly":"weekly"}</changefreq><priority>${url==="/"?"1.0":url==="/shop/"?"0.9":"0.7"}</priority></url>`),'</urlset>',''].join("\n");
fs.writeFileSync(path.join(root,"sitemap.xml"),xml,"utf8");
console.log(`Built sitemap with ${urls.length} extensionless URLs.`);