(function(){
const data={
"rice.html":["Buy premium rice online in Bangladesh","Rice is an essential part of everyday meals, but choosing the right rice can make a noticeable difference in taste, nutrition, and overall food quality. At Girosto, you can buy carefully selected rice suitable for daily cooking, traditional recipes, family meals, and special occasions.","Rice for every Bangladeshi table","daily meals, khichuri, biryani, pitha, and special occasions"],
"mustard-oil.html":["Buy pure mustard oil at Girosto","Mustard oil is an essential ingredient in many Bangladeshi kitchens. Its distinctive aroma and natural pungency add authentic flavor to fish curries, bhorta, vegetables, pickles, meat dishes, and other traditional recipes. However, finding pure mustard oil can be challenging because many products available in the market may be blended, excessively refined, or made from low-quality mustard seeds.","Traditional aroma, carefully sourced","curries, bhorta, pickles, marinades, and everyday cooking"],
"healthy-oils.html":["Buy premium healthy oil at Girosto","Cooking oil is used in almost every meal, but choosing the right oil can be confusing. Many products available in the market may be overly refined, poorly packaged or unsuitable for specific cooking methods, making it difficult for families to select an oil that matches their daily cooking and lifestyle needs.","The right oil for every routine","cooking, baking, dressing, wellness, hair care, and skin care"],
"lentils-pulses.html":["Buy premium lentils & pulses at Girosto","Lentils and pulses are essential ingredients in everyday meals, providing variety, taste, and convenience to family cooking. However, poorly cleaned grains, inconsistent quality, excess moisture, and unreliable packaging can make it difficult to choose products that cook evenly and maintain their natural flavor.","Everyday nutrition made simple","dal, khichuri, soups, curries, and affordable family meals"],
"ground-spices.html":["Buy premium ground spices at Girosto","Ground spices are essential for adding color, aroma, and authentic flavor to everyday meals. However, many packaged spices may lose their natural freshness over time or contain inconsistent blends, excess coloring, and low-quality ingredients, making it difficult to achieve the desired taste in home cooking.","Fresh flavour, ready to use","curries, marinades, bhorta, vegetables, meat, fish, and festive dishes"],
"whole-spices.html":["Buy premium whole spices at Girosto","Whole spices bring deeper aroma, natural flavor, and authentic character to everyday cooking. However, old stock, excess moisture, weak fragrance, and poorly stored spices can affect the taste of curries, biryani, meat dishes, pickles, and other traditional recipes.","Aromatic ingredients for real cooking","biryani, curry, tea, desserts, tempering, and festive meals"],
"sugar.html":["Premium Sugar in Bangladesh","Shop carefully selected sugar options for tea, desserts, baking, drinks, and regular kitchen use according to household preferences.","Reliable sweetness for every recipe","tea, coffee, baking, desserts, drinks, preserves, and everyday cooking"],
"jaggery.html":["Premium Jaggery in Bangladesh","Discover a traditional sweetener valued for rich flavour and versatility in pitha, payesh, desserts, drinks, and homemade recipes.","Traditional sweetness, naturally rich","pitha, payesh, desserts, tea, drinks, chutneys, and seasonal recipes"],
"homemade-pickles.html":["Homemade Pickles in Bangladesh","Enjoy familiar homemade flavours prepared with selected fruits, vegetables, spices, and oils—the perfect pairing for everyday meals.","A bright, bold addition to every plate","rice, khichuri, paratha, snacks, travel meals, and traditional dishes"],
"healthy-seeds.html":["Premium Healthy Seeds in Bangladesh","Explore chia, flax, sesame, pumpkin, sunflower, and other versatile seeds for simple additions to a balanced daily diet.","Small ingredients, versatile routines","smoothies, breakfast bowls, salads, baking, yoghurt, and healthy snacks"],
"hair-skin-care.html":["Hair & Skin Care Oils in Bangladesh","Discover natural personal-care oils and wellness products selected for practical, regular hair and skin care routines.","Thoughtful care, naturally inspired","hair oiling, scalp care, skin hydration, massage, and personal wellness routines"],
"dairy-poultry.html":["Premium Dairy & Poultry in Bangladesh","Find responsibly sourced household favourites and everyday essentials for nourishing family meals and healthy cooking.","Fresh essentials for family meals","breakfast, baking, desserts, snacks, curries, and everyday meal preparation"],
"daily-needs.html":["Daily Healthy Food in Bangladesh","Make regular shopping easier with useful grocery and household essentials brought together in one trusted online destination.","Better everyday choices in one place","family groceries, breakfast, lunch boxes, pantry restocking, and daily routines"],
"girosto-special.html":["Girosto Special Items in Bangladesh","Discover signature selections chosen for their unique quality, traditional taste, customer demand, or everyday usefulness.","Distinctive finds, selected by Girosto","gifting, special occasions, family favourites, discovery, and seasonal enjoyment"],
"honey.html":["Original Honey in Bangladesh","Explore naturally sourced honey varieties selected for authentic flavour, aroma, and texture for everyday household use.","Naturally sweet, endlessly useful","breakfast, drinks, desserts, marinades, snacks, and everyday consumption"],
"dates-dry-fruits.html":["Premium Dates & Dry Fruits in Bangladesh","Choose from popular Middle Eastern dates, dried fruits, Aam Sotto, and specialty products for snacking, gifting, and everyday meals.","Naturally flavourful food for every occasion","Ramadan, gifting, breakfast, desserts, travel, and regular snacking"],
"nuts.html":["Premium Nuts in Bangladesh","Explore cashews, almonds, walnuts, pistachios, peanuts, seeds, and mixed nuts selected for freshness, texture, and crunch.","Premium crunch for snacks and recipes","snacking, baking, salads, breakfast bowls, desserts, smoothies, and gifting"],
"herb-powders.html":["Organic Herb Powders in Bangladesh","Explore selected herbal powders with clear product information for traditional wellness, food preparation, and personal-care routines.","Traditional ingredients, practical guidance","drinks, cooking, hair care, skin care, and mindful wellness routines"],
"health-items.html":["Genuine Health Items in Bangladesh","Find useful products selected for customers who want convenient, informed, and responsible choices for a mindful lifestyle.","Everyday support for healthier living","wellness routines, household care, meal planning, and informed daily choices"],
"fresh-fruits.html":["Organic Fresh Fruits in Bangladesh","Enjoy seasonal fruits selected for quality, taste, and household convenience through dependable sourcing and reliable delivery.","Fresh, seasonal, and family friendly","snacking, breakfast, juice, desserts, lunch boxes, and family meals"]};
const key=document.body.dataset.category, item=data[key]||["Organic Food Collection","Explore a carefully selected Girosto collection for healthier everyday living.","A trusted collection for your family","everyday meals and household needs"];
document.title=item[0]+" | Girosto";document.querySelector('meta[name="description"]').content=item[1];
document.getElementById("categoryName").textContent=item[0];document.getElementById("categoryIntro").textContent=item[1];document.getElementById("collectionTitle").textContent=item[2];document.getElementById("usage").textContent=item[3];
const related=[...Object.entries(data)].filter(x=>x[0]!==key).slice(0,6);document.getElementById("related").innerHTML=related.map(x=>`<a href="${x[0]}">${x[1][0]}</a>`).join("");
})();

