(function(){
const data={
"rice.html":["Buy premium rice online in Bangladesh","Rice is an essential part of everyday meals, but choosing the right rice can make a noticeable difference in taste, nutrition, and overall food quality. At Girosto, you can buy carefully selected rice suitable for daily cooking, traditional recipes, family meals, and special occasions.","Rice for every Bangladeshi table","daily meals, khichuri, biryani, pitha, and special occasions"],
"mustard-oil.html":["Buy pure mustard oil at Girosto","Mustard oil is an essential ingredient in many Bangladeshi kitchens. Its distinctive aroma and natural pungency add authentic flavor to fish curries, bhorta, vegetables, pickles, meat dishes, and other traditional recipes. However, finding pure mustard oil can be challenging because many products available in the market may be blended, excessively refined, or made from low-quality mustard seeds.","Traditional aroma, carefully sourced","curries, bhorta, pickles, marinades, and everyday cooking"],
"healthy-oils.html":["Buy premium healthy oil at Girosto","Cooking oil is used in almost every meal, but choosing the right oil can be confusing. Many products available in the market may be overly refined, poorly packaged or unsuitable for specific cooking methods, making it difficult for families to select an oil that matches their daily cooking and lifestyle needs.","The right oil for every routine","cooking, baking, dressing, wellness, hair care, and skin care"],
"lentils-pulses.html":["Buy premium lentils & pulses at Girosto","Lentils and pulses are essential ingredients in everyday meals, providing variety, taste, and convenience to family cooking. However, poorly cleaned grains, inconsistent quality, excess moisture, and unreliable packaging can make it difficult to choose products that cook evenly and maintain their natural flavor.","Everyday nutrition made simple","dal, khichuri, soups, curries, and affordable family meals"],
"ground-spices.html":["Buy premium ground spices at Girosto","Ground spices are essential for adding color, aroma, and authentic flavor to everyday meals. However, many packaged spices may lose their natural freshness over time or contain inconsistent blends, excess coloring, and low-quality ingredients, making it difficult to achieve the desired taste in home cooking.","Fresh flavour, ready to use","curries, marinades, bhorta, vegetables, meat, fish, and festive dishes"],
"whole-spices.html":["Buy premium whole spices at Girosto","Whole spices bring deeper aroma, natural flavor, and authentic character to everyday cooking. However, old stock, excess moisture, weak fragrance, and poorly stored spices can affect the taste of curries, biryani, meat dishes, pickles, and other traditional recipes.","Aromatic ingredients for real cooking","biryani, curry, tea, desserts, tempering, and festive meals"],
"sugar.html":["Buy premium sugar at Girosto","Sugar is a common ingredient in tea, coffee, desserts, baking, and everyday recipes. However, inconsistent quality, excessive processing, poor packaging, and uncertain sourcing can make it difficult to choose the right sugar for your family's daily needs.","Reliable sweetness for every recipe","tea, coffee, baking, desserts, drinks, preserves, and everyday cooking"],
"jaggery.html":["Buy jaggery at Girosto","Jaggery is widely used in traditional sweets, pitha, payesh, desserts, and everyday recipes across Bangladesh. However, finding authentic jaggery with its natural aroma, flavor, and proper texture can be difficult because many products may contain excess sugar, artificial coloring, or inconsistent ingredients.","Traditional sweetness, naturally rich","pitha, payesh, desserts, tea, drinks, chutneys, and seasonal recipes"],
"homemade-pickles.html":["Homemade pickles at Girosto","Homemade pickles bring bold flavor, traditional aroma, and a satisfying balance of sweet, sour, and spicy notes to everyday meals. However, finding pickles with authentic taste, carefully selected ingredients, and consistent quality can be difficult, especially when many products contain excessive preservatives, artificial flavors, or unbalanced seasoning.","A bright, bold addition to every plate","rice, khichuri, paratha, snacks, travel meals, and traditional dishes"],
"healthy-seeds.html":["Premium healthy seeds at Girosto","Healthy seeds have become a popular addition to modern diets because they are easy to include in drinks, breakfast bowls, salads, and everyday recipes. However, poor-quality seeds, excess moisture, dust, and improper packaging can affect their freshness, texture, and overall usability.","Small ingredients, versatile routines","smoothies, breakfast bowls, salads, baking, yoghurt, and healthy snacks"],
"hair-skin-care.html":["Premium essential oil for hair & skin care at Girosto","Choosing the right oil for hair and skin care can be confusing when products vary in quality, purity, and intended use. Poorly stored or unsuitable oils may feel heavy, cause discomfort, or fail to fit your personal care routine, making reliable product selection especially important.","Thoughtful care, naturally inspired","hair oiling, scalp care, skin hydration, massage, and personal wellness routines"],
"dairy-poultry.html":["Premium dairy & poultry at Girosto","Milk and eggs are everyday household essentials used for breakfast, cooking, baking, and family nutrition. However, uncertain sourcing, improper handling, and inconsistent freshness can make it difficult to choose dependable dairy and poultry products for regular consumption.","Fresh essentials for family meals","breakfast, baking, desserts, snacks, curries, and everyday meal preparation"],
"daily-needs.html":["Buy your daily healthy food in Bangladesh","Healthy eating often begins with the ingredients used in everyday meals. However, finding fresh, authentic, and properly packaged food products can be difficult when quality varies between sellers and important information about sourcing, ingredients, or storage is unavailable.","Better everyday choices in one place","family groceries, breakfast, lunch boxes, pantry restocking, and daily routines"],
"girosto-special.html":["Girosto special items in Bangladesh","Traditional and homemade food items remain an important part of everyday meals in Bangladesh. However, finding authentic, hygienically prepared and properly packed products can be difficult, especially when ingredients, production methods and freshness are not clearly explained.","Distinctive finds, selected by Girosto","gifting, special occasions, family favourites, discovery, and seasonal enjoyment"],
"honey.html":["Original honey in Bangladesh","Honey is a popular natural food in Bangladesh, but finding genuinely original honey is not always easy. Many products available in the market may contain added sugar, artificial flavor, excessive processing, or unclear sourcing, making it difficult for customers to identify authentic honey.","Naturally sweet, endlessly useful","breakfast, drinks, desserts, marinades, snacks, and everyday consumption"],
"dates-dry-fruits.html":["Premium dates & dry fruits in Bangladesh","Dates and dry fruits are convenient, naturally flavorful foods for snacking, gifting, and everyday meals. However, customers often struggle to find products that are fresh, properly stored, and sourced from dependable suppliers. Poor packaging or extended storage may affect their taste, texture, and overall quality.","Naturally flavourful food for every occasion","Ramadan, gifting, breakfast, desserts, travel, and regular snacking"],
"nuts.html":["Premium nuts in Bangladesh","Nuts and seeds are popular choices for snacking, breakfast, baking, and preparing everyday meals. However, finding fresh, properly packed, and good-quality nuts can be challenging, as some products may lose their natural taste, crunch, and aroma due to poor storage or handling.","Premium crunch for snacks and recipes","snacking, baking, salads, breakfast bowls, desserts, smoothies, and gifting"],
"herb-powders.html":["Organic herb powder in Bangladesh","Herb powders are commonly used in traditional recipes, beverages, skincare routines, and everyday wellness practices. However, choosing the right product can be difficult when the source, purity, processing method, or packaging quality is unclear.","Traditional ingredients, practical guidance","drinks, cooking, hair care, skin care, and mindful wellness routines"],
"health-items.html":["Genuine health items in Bangladesh","Health-focused food products have become part of many people's daily routines, from natural drinks and traditional ingredients to pantry essentials. However, finding genuine health items can be difficult when product quality, sourcing, packaging, and usage information are not clearly presented.","Everyday support for healthier living","wellness routines, household care, meal planning, and informed daily choices"],
"fresh-fruits.html":["Organic fresh fruits in Bangladesh","Fresh fruits are an important part of everyday meals, but finding naturally grown, properly handled, and fresh-quality fruits can be difficult. Many buyers are concerned about excessive chemicals, poor storage, artificial ripening, and fruits that lose their natural taste before reaching the customer.","Fresh, seasonal, and family friendly","snacking, breakfast, juice, desserts, lunch boxes, and family meals"]};
const key=document.body.dataset.category, item=data[key]||["Organic Food Collection","Explore a carefully selected Girosto collection for healthier everyday living.","A trusted collection for your family","everyday meals and household needs"];
document.title=item[0]+" | Girosto";document.querySelector('meta[name="description"]').content=item[1];
document.getElementById("categoryName").textContent=item[0];document.getElementById("categoryIntro").textContent=item[1];document.getElementById("collectionTitle").textContent=item[2];document.getElementById("usage").textContent=item[3];
const related=[...Object.entries(data)].filter(x=>x[0]!==key).slice(0,6);document.getElementById("related").innerHTML=related.map(x=>`<a href="${x[0]}">${x[1][0]}</a>`).join("");
})();

