(function(){
const categories=[["Rice","bi-basket2","BuyOrganicRiceOnlineinBangladeshGirosto.html"],["Mustard Oil","bi-droplet-half","BuyPureMustardOilOnlineinBangladeshGirosto.html"],["Healthy Oils","bi-moisture","BuyPremiumHealthyOilOnlineinBangladeshGirosto.html"],["Lentils & Pulses","bi-circle-half","BuyPremiumLentilsPulsesinBangladeshGirosto.html"],["Ground Spices","bi-fire","BuyPremiumGroundSpicesinBangladeshGirosto.html"],["Whole Spices","bi-stars","BuyPremiumWholeSpicesinBangladeshGirosto.html"],["Sugar","bi-hexagon","BuyPremiumSugarOnlineinBangladeshGirosto.html"],["Jaggery","bi-brightness-alt-high","BuyPremiumJaggeryinBangladeshGirosto.html"],["Homemade Pickles","bi-jar","HomemadePicklesinBangladeshGirosto.html"],["Healthy Seeds","bi-flower1","BuyPremiumHealthySeedsinBangladeshGirosto.html"],["Hair & Skin Care","bi-heart","HairskincareoilsinBangladeshGirosto.html"],["Dairy & Poultry","bi-egg","BuyPremiumDairyPoultryinBangladeshGirosto.html"],["Daily Needs","bi-bag-check","BuyDailyHealthyFoodinBangladesh.html"],["Girosto Special","bi-award","GirostoSpecialItemsinBangladesh.html"],["Original Honey","bi-droplet","OriginalHoneyinBangladesh.html"],["Dates & Dry Fruits","bi-sun","PremiumDatesDryFruitsinBangladesh.html"],["Premium Nuts","bi-nut","PremiumNutsinBangladesh.html"],["Herb Powders","bi-flower3","OrganicHerbPowderinBangladesh.html"],["Health Items","bi-activity","GenuineHealthItemsinBangladesh.html"],["Fresh Fruits","bi-apple","OrganicFreshFruitsinBangladesh.html"]];
const products=[["Aromatic Rice","Naturally processed pantry staple","bi-basket2","BuyOrganicRiceOnlineinBangladeshGirosto.html"],["Cold-Pressed Mustard Oil","Traditional flavour for everyday cooking","bi-droplet-half","BuyPureMustardOilOnlineinBangladeshGirosto.html"],["Original Honey","Naturally sourced with authentic taste","bi-droplet","OriginalHoneyinBangladesh.html"],["Premium Nuts","Fresh crunch for snacks and recipes","bi-nut","PremiumNutsinBangladesh.html"]];
const faqs=[["Is organic food healthier than regular food?","Organic food may help reduce exposure to certain artificial additives and farming chemicals. Overall health also depends on food variety, portion size, nutritional balance, and individual dietary needs."],["How can I identify genuine organic products?","Check the label, ingredients, source information, packaging, producer details, and available certifications. Transparent product information helps you make a better-informed choice."],["Where can I buy organic food in Bangladesh?","You can purchase from trusted physical stores, farms, and online shops. Girosto brings organic groceries, natural food items, and daily essentials together for customers in Bangladesh."],["Why is organic food more expensive?","Smaller production volumes, natural farming methods, careful processing, specialised sourcing, and quality-control requirements can affect the price."],["Does organic food contain pesticides?","Organic farming generally limits synthetic pesticides, though approved natural pest-control methods may be used. Review product sourcing details when needed."],["How should organic food be stored?","Keep dry foods in airtight containers in a cool, dry place. Dairy, fruits, and other perishable items may require refrigeration."],["Is organic food suitable for children?","Many organic foods can be part of a balanced, age-appropriate diet. Parents should consider allergies, nutritional needs, and professional medical advice."],["What organic products are popular in Bangladesh?","Common choices include rice, mustard oil, honey, lentils, spices, jaggery, seeds, nuts, dry fruits, herbal powders, and seasonal fruits."],["Does Girosto deliver across Bangladesh?","Delivery time, cost, and product availability vary by location and selected items. Contact our team to confirm service for your address."]];
const grid=document.getElementById("categoryGrid");if(grid)grid.innerHTML=categories.map(c=>`<a class="cat-card" href="shop/category/${c[2]}"><i class="bi ${c[1]}" aria-hidden="true"></i><span>${c[0]}</span></a>`).join("");
const productGrid=document.getElementById("bestSellerGrid");if(productGrid)productGrid.innerHTML=products.map(p=>`<div class="col-sm-6 col-lg-3"><article class="product-card"><div class="product-media"><span class="tag">Customer favourite</span><i class="bi ${p[2]}" aria-hidden="true"></i></div><div class="product-body"><h3>${p[0]}</h3><p>${p[1]}</p><a href="shop/category/${p[3]}">Explore collection <i class="bi bi-arrow-right"></i></a></div></article></div>`).join("");
const faq=document.getElementById("faqAcc");if(faq)faq.innerHTML=faqs.map((f,i)=>`<div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button ${i?"collapsed":""}" type="button" data-bs-toggle="collapse" data-bs-target="#faq-${i}" aria-expanded="${!i}">${f[0]}</button></h3><div id="faq-${i}" class="accordion-collapse collapse ${i?"":"show"}" data-bs-parent="#faqAcc"><div class="accordion-body">${f[1]}</div></div></div>`).join("");
const year=document.getElementById("year");if(year)year.textContent=new Date().getFullYear();
})();

